name: decision_board_system
description: Decision Board System.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dio: ^4.0.6
  stack_trace: ^1.10.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  flutter_secure_storage: ^7.0.1
  get_it: ^7.2.0
  bottom_drawer: ^0.0.5
  csv: ^5.0.1
  fl_chart: ^0.61.0
  file_picker: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/decision_board_logo.png
